# Generated by Django 5.1.6 on 2025-02-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workers', models.ManyToManyField(related_name='forms', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.form')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.form')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('single_choice_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('multiple_choice_answer', models.JSONField(blank=True, default=list, null=True)),
                ('form_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.formanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.question')),
            ],
        ),
    ]
