# Generated by Django 5.1.6 on 2025-02-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in forms and reports')),
                ('show_in_table', models.BooleanField(default=False, help_text='Display questions in this category as table rows')),
                ('columns', models.JSONField(blank=True, default=list, help_text='JSON list of column names for table display')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='show_in_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='form.questioncategory'),
        ),
    ]
