# Generated by Django 5.1.6 on 2025-02-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_questioncategory_question_columns_question_is_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_questions', to='form.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
