# Generated by Django 5.1.6 on 2025-02-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_question_depends_on_question_media_url_and_more'),
        ('tasks', '0008_taskattachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
    ]
