# Generated by Django 5.1.6 on 2025-02-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('data', '0002_taskcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmachine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.taskcategory'),
        ),
    ]
