# Generated by Django 5.1.6 on 2025-02-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientplace_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='clientmachine',
            name='location_notes',
        ),
        migrations.RemoveField(
            model_name='clientplace',
            name='notes',
        ),
    ]
