# Generated by Django 5.1.6 on 2025-02-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientmachine_category'),
        ('data', '0003_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='objects',
            new_name='client_objects',
        ),
        migrations.AlterField(
            model_name='clientmachine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.taskcategory'),
        ),
    ]
