# Generated by Django 5.1.6 on 2025-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_objects_client_client_objects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientobject',
            name='machines',
            field=models.ManyToManyField(blank=True, to='client.clientmachine'),
        ),
    ]
