# Generated by Django 5.1.6 on 2025-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientobject_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmachine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
