# Generated by Django 5.1.6 on 2025-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientmachine_description'),
        ('tasks', '0010_alter_task_client_alter_task_client_machines_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientObject',
            new_name='ClientPlace',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientmachine',
            options={'verbose_name': 'Client machine', 'verbose_name_plural': 'Client machines'},
        ),
        migrations.AlterModelOptions(
            name='clientplace',
            options={'verbose_name': 'Client place', 'verbose_name_plural': 'Client places'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_objects',
        ),
        migrations.AddField(
            model_name='client',
            name='client_places',
            field=models.ManyToManyField(blank=True, related_name='places', to='client.clientplace'),
        ),
    ]
