# Generated by Django 5.1.6 on 2025-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_clientobject_clientplace_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientplace',
            name='machines',
        ),
        migrations.AddField(
            model_name='clientplace',
            name='client_machines',
            field=models.ManyToManyField(blank=True, related_name='machines', to='client.clientmachine'),
        ),
    ]
