# Generated by Django 5.1.6 on 2025-02-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_clientplace_machines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientplace',
            name='client_machines',
        ),
        migrations.AddField(
            model_name='clientmachine',
            name='client_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='client.clientplace'),
        ),
        migrations.AddField(
            model_name='clientmachine',
            name='identifier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientmachine',
            unique_together={('client_place', 'identifier')},
        ),
    ]
