# Generated by Django 5.1.6 on 2025-02-22 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('ff0000', 'Red'), ('0000ff', 'Blue'), ('00ff00', 'Green'), ('ffff00', 'Yellow'), ('ffa500', 'Orange'), ('800080', 'Purple'), ('ffc0cb', 'Pink'), ('000000', 'Black'), ('ffffff', 'White'), ('808080', 'Gray'), ('00ffff', 'Cyan'), ('ff00ff', 'Magenta'), ('a52a2a', 'Brown')], default='808080', max_length=6)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('duration_length_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Task category',
                'verbose_name_plural': 'Task categories',
            },
        ),
    ]
