# Generated by Django 5.1.6 on 2025-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('change_basic_task_status', 'Change basic task status'), ('change_all_task_status', 'Change all task status'), ('delete_task', 'Delete Task'), ('edit_task', 'Edit Task')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('features', models.ManyToManyField(blank=True, to='data.feature')),
            ],
        ),
    ]
