# Generated by Django 5.1.6 on 2025-02-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientmachine_category'),
        ('data', '0002_taskcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
