# Generated by Django 5.1.6 on 2025-02-25 20:23

import data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_feature_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'unique_together': {('name', 'color')},
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.ForeignKey(blank=True, default=data.models.Color.default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.color'),
        ),
    ]
