# Generated by Django 5.1.6 on 2025-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('ff0000', 'Red'), ('0000ff', 'Blue'), ('00ff00', 'Green'), ('ffff00', 'Yellow'), ('ffa500', 'Orange'), ('800080', 'Purple'), ('ffc0cb', 'Pink'), ('000000', 'Black'), ('ffffff', 'White'), ('808080', 'Gray'), ('00ffff', 'Cyan'), ('ff00ff', 'Magenta'), ('a52a2a', 'Brown')], default='808080', max_length=6),
        ),
    ]
