# Generated by Django 5.1.6 on 2025-02-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_key', models.CharField(blank=True, max_length=36, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('mod', 'Moderator'), ('admin', 'Administrator')], default='worker', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.worker')),
            ],
        ),
    ]
