# Generated by Django 5.1.6 on 2025-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_workerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlocation',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerlocation',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
