# Generated by Django 5.1.6 on 2025-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_workerlocation_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('mod', 'Moderator'), ('admin', 'Administrator')], default='worker', max_length=50),
        ),
    ]
