# Generated by Django 5.1.6 on 2025-02-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasknote',
            old_name='created_by',
            new_name='worker',
        ),
    ]
