# Generated by Django 5.1.6 on 2025-02-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='OrderType',
            new_name='TaskType',
        ),
    ]
