# Generated by Django 5.1.6 on 2025-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_order_task_rename_ordertype_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
