# Generated by Django 5.1.6 on 2025-02-17 11:19

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
