# Generated by Django 5.1.6 on 2025-02-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskstatus_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='require_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
