# Generated by Django 5.1.6 on 2025-02-25 20:23

import data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_color_alter_tag_color'),
        ('tasks', '0004_taskstatus_require_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='color',
            field=models.ForeignKey(blank=True, default=data.models.Color.default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.color'),
        ),
    ]
