# Generated by Django 5.1.6 on 2025-02-17 11:32

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
