# Generated by Django 5.1.6 on 2025-02-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskstatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
