# Generated by Django 5.1.6 on 2025-02-26 10:58

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskstatus_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.task_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.task_image_upload_path),
        ),
    ]
