# Generated by Django 5.1.6 on 2025-02-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('data', '0001_initial'),
        ('tasks', '0007_task_created_at_task_deadline_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='client.client'),
        ),
        migrations.AddField(
            model_name='task',
            name='client_machines',
            field=models.ManyToManyField(blank=True, related_name='client_machines', to='client.clientmachine'),
        ),
        migrations.AddField(
            model_name='task',
            name='client_objects',
            field=models.ManyToManyField(blank=True, related_name='client_objects', to='client.clientobject'),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_realization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_realization_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data.tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('not_started', 'Not started'), ('awaiting_confirmation', 'Awaiting confirmation')], default='not_started', max_length=50),
        ),
    ]
