# Generated by Django 5.1.6 on 2025-02-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskattachment_file_alter_taskattachment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='type',
            field=models.CharField(blank=True, choices=[('client_signature', 'Client Signature'), ('worker_signature', 'Worker Signature')], max_length=50, null=True),
        ),
    ]
