# Generated by Django 5.1.6 on 2025-02-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_taskcategory'),
        ('tasks', '0008_task_client_task_client_machines_task_client_objects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.taskcategory'),
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
