# Generated by Django 5.1.6 on 2025-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskattachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='type',
            field=models.CharField(blank=True, choices=[('client_signature', 'Client Signature'), ('worker_signature', 'Worker Signature'), ('form', 'Form')], max_length=50, null=True),
        ),
    ]
