# Generated by Django 5.1.6 on 2025-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskattachment_type'),
        ('worker', '0003_alter_worker_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='worker.worker'),
        ),
    ]
