# Generated by Django 5.1.6 on 2025-02-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_objects_client_client_objects_and_more'),
        ('tasks', '0009_remove_task_type_task_category_delete_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_clients', to='client.client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_machines',
            field=models.ManyToManyField(blank=True, related_name='related_client_machines', to='client.clientmachine'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_objects',
            field=models.ManyToManyField(blank=True, related_name='related_client_objects', to='client.clientobject'),
        ),
    ]
