# Generated by Django 5.1.6 on 2025-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_clientobject_clientplace_alter_client_options_and_more'),
        ('tasks', '0010_alter_task_client_alter_task_client_machines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='client_objects',
        ),
        migrations.AddField(
            model_name='task',
            name='client_places',
            field=models.ManyToManyField(blank=True, related_name='related_client_places', to='client.clientplace'),
        ),
    ]
